### ISSUE TITLE
performance benchmark issue

### ISSUE THREAD

**Issue by yongbingchen** [dbus2/busd#107]
I found the performance is much worse than bus1 "dbus-broker" service on my OpenBMC platform "armv7-unknown-linux-gnueabihf", a 2-core SoC, the binary is built simply from below command:
```
~/workspace/zbus_broker/busd$ git log -1
commit ecfb268c3bb594f2a080df34d7214fd260f585fe (HEAD -> main, origin/main, origin/HEAD)
~/workspace/zbus_broker/busd$ cross build --release --target armv7-unknown-linux-gnueabihf
```

I modified the systemd/src/libsystemd/sd-bus/test-bus-benchmark.c test case, for it to run only 15000 round of IPCs.

For bus1 dbus-broker, I can get about 1050 round of IPC per second (but it will reach a system wide total bandwidth at 2100 round of IPC per second, if I run two test in parallel), but now I can get only 400 round of IPC per second on same platform (HW and SW):

```
root@xxxxxx:/tmp# time ./test-bus-benchmark
Total round: 15000
Copying/memfd are equally fast at 32768 bytes

real    0m38.844s
user    0m8.254s
sys     0m9.658s
```

Also, run two test in parallel, the performance also dropped like it's running on single thread(supposedly they shouldn't, as zbus support full parallelism, and I have a 2core SoC, and I can see the busd process is running in two threads from perf):
``` 
root@xxxx:/tmp# for i in {0..1}; do time /tmp/test-bus-benchmark & done
[2] 10105
[3] 10106
root@xxxx:/tmp# Total round: 15000
Copying/memfd are equally fast at 32768 bytes

real    1m15.207s
user    0m10.025s
sys     0m13.641s
Total round: 15000
Copying/memfd are equally fast at 32768 bytes

real    1m15.705s
user    0m10.562s
sys     0m13.344s
```

Please below source code for the benchmark test case.

```
/***
  This file is part of systemd.

  Copyright 2013 Lennart Poettering

  systemd is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation; either version 2.1 of the License, or
  (at your option) any later version.

  systemd is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with systemd; If not, see <http://www.gnu.org/licenses/>.
***/

#include <assert.h>
#include <stdint.h>
#include <sys/cdefs.h>
#include <sys/wait.h>
#include <sys/resource.h>
#define _GNU_SOURCE
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdbool.h>

#include <sys/wait.h>
#include <unistd.h>

#include "sd-bus.h"

#include "alloc-util.h"
#include "bus-internal.h"
#include "constants.h"
#include "fd-util.h"
#include "missing_resource.h"
#include "string-util.h"
#include "time-util.h"

#define MAX_SIZE (16*1024)

static usec_t arg_loop_usec = 1000 * USEC_PER_MSEC;

typedef enum Type {
        TYPE_LEGACY,
        TYPE_DIRECT,
} Type;

static void server(sd_bus *b, size_t *result) {
        int r;

        for (;;) {
                _cleanup_(sd_bus_message_unrefp) sd_bus_message *m = NULL;

                r = sd_bus_process(b, &m);
                assert_se(r >= 0);

                if (r == 0)
                        assert_se(sd_bus_wait(b, USEC_INFINITY) >= 0);
                if (!m)
                        continue;

                if (sd_bus_message_is_method_call(m, "benchmark.server", "Ping"))
                        assert_se(sd_bus_reply_method_return(m, NULL) >= 0);
                else if (sd_bus_message_is_method_call(m, "benchmark.server", "Work")) {
                        const void *p;
                        size_t sz;

                        /* Make sure the mmap is mapped */
                        assert_se(sd_bus_message_read_array(m, 'y', &p, &sz) > 0);

                        r = sd_bus_reply_method_return(m, NULL);
                        assert_se(r >= 0);
                } else if (sd_bus_message_is_method_call(m, "benchmark.server", "Exit")) {
                        uint64_t res;
                        assert_se(sd_bus_message_read(m, "t", &res) > 0);

                        *result = res;
                        return;

                } else if (!sd_bus_message_is_signal(m, NULL, NULL))
                        assert_not_reached();
        }
}

static int quit_callback(sd_bus_message *m, void *userdata, sd_bus_error *ret_error) {
        bool *quit = userdata;
        *quit = true;
        return 1;
}

static void transaction(sd_bus *b, size_t sz, const char *server_name) {
        _cleanup_(sd_bus_message_unrefp) sd_bus_message *m = NULL, *reply = NULL;
        uint8_t *p;

        assert_se(sd_bus_message_new_method_call(b, &m, server_name, "/", "benchmark.server", "Work") >= 0);
        assert_se(sd_bus_message_append_array_space(m, 'y', sz, (void**) &p) >= 0);

        memset(p, 0x80, sz);

        bool quit = false;
        // assert_se(sd_bus_call(b, m, 0, NULL, &reply) >= 0);
        assert_se(sd_bus_call_async(b, NULL, m, quit_callback, &quit, 2000 * USEC_PER_MSEC) >= 0);
        while (!quit) {
                int r = sd_bus_process(b, NULL);
                assert_se(r >= 0);
                if (r == 0)
                        assert_se(sd_bus_wait(b, 100) >= 0);
        }
}

static void client_bisect(const char *address, const char *server_name) {
        _cleanup_(sd_bus_message_unrefp) sd_bus_message *x = NULL;
        size_t lsize, rsize, csize;
        sd_bus *b;
        int r;

        r = sd_bus_new(&b);
        assert_se(r >= 0);

        r = sd_bus_set_address(b, address);
        assert_se(r >= 0);

        r = sd_bus_start(b);
        assert_se(r >= 0);

        r = sd_bus_call_method(b, server_name, "/", "benchmark.server", "Ping", NULL, NULL, NULL);
        assert_se(r >= 0);

        lsize = 1;
        rsize = MAX_SIZE;

        b->use_memfd = 0;
        unsigned total_round = 0;
        for (csize = 1; csize <= MAX_SIZE; csize *= 2) {
                usec_t t;
                unsigned n_memfd;

                for (n_memfd = 0; n_memfd < 1000; n_memfd++) {
                        transaction(b, csize, server_name);
                }

                total_round += n_memfd;
        }

        printf("Total round: %u\n", total_round);

        b->use_memfd = 1;
        assert_se(sd_bus_message_new_method_call(b, &x, server_name, "/", "benchmark.server", "Exit") >= 0);
        assert_se(sd_bus_message_append(x, "t", csize) >= 0);
        assert_se(sd_bus_send(b, x, NULL) >= 0);

        sd_bus_unref(b);
}

static void client_chart(Type type, const char *address, const char *server_name, int fd) {
        _cleanup_(sd_bus_message_unrefp) sd_bus_message *x = NULL;
        size_t csize = 16;
        sd_bus *b;
        int r;

        r = sd_bus_new(&b);
        assert_se(r >= 0);

        if (type == TYPE_DIRECT) {
                r = sd_bus_set_fd(b, fd, fd);
                assert_se(r >= 0);
        } else {
                r = sd_bus_set_address(b, address);
                assert_se(r >= 0);

                r = sd_bus_set_bus_client(b, true);
                assert_se(r >= 0);
        }

        r = sd_bus_start(b);
        assert_se(r >= 0);

        r = sd_bus_call_method(b, server_name, "/", "benchmark.server", "Ping", NULL, NULL, NULL);
        assert_se(r >= 0);

        b->use_memfd = 0;
        unsigned total_round = 0;
        for (csize = 1; csize <= MAX_SIZE; csize *= 2) {
                usec_t t;
                unsigned n_memfd;

                for (n_memfd = 0; n_memfd < 1000; n_memfd++) {
                        transaction(b, csize, server_name);
                }

                total_round += n_memfd;
        }

        printf("Total round: %u\n", total_round);
        b->use_memfd = 1;
        assert_se(sd_bus_message_new_method_call(b, &x, server_name, "/", "benchmark.server", "Exit") >= 0);
        assert_se(sd_bus_message_append(x, "t", csize) >= 0);
        assert_se(sd_bus_send(b, x, NULL) >= 0);

        sd_bus_unref(b);
}

int main(int argc, char *argv[]) {
        enum {
                MODE_BISECT,
                MODE_CHART,
        } mode = MODE_BISECT;
        Type type = TYPE_LEGACY;
        int i, pair[2] = { -1, -1 };
        _cleanup_free_ char *name = NULL, *bus_name = NULL, *address = NULL, *server_name = NULL;
        _cleanup_close_ int bus_ref = -1;
        const char *unique;
        cpu_set_t cpuset;
        size_t result;
        sd_bus *b;
        pid_t pid;
        int r;

        for (i = 1; i < argc; i++) {
                if (streq(argv[i], "chart")) {
                        mode = MODE_CHART;
                        continue;
                } else if (streq(argv[i], "legacy")) {
                        type = TYPE_LEGACY;
                        continue;
                } else if (streq(argv[i], "direct")) {
                        type = TYPE_DIRECT;
                        continue;
                }

                assert_se(parse_sec(argv[i], &arg_loop_usec) >= 0);
        }

        assert_se(arg_loop_usec > 0);

        if (type == TYPE_LEGACY) {
                const char *e;

                e = secure_getenv("DBUS_SESSION_BUS_ADDRESS");
                assert_se(e);

                address = strdup(e);
                assert_se(address);
        }

        r = sd_bus_new(&b);
        assert_se(r >= 0);

        if (type == TYPE_DIRECT) {
                assert_se(socketpair(AF_UNIX, SOCK_STREAM, 0, pair) >= 0);

                r = sd_bus_set_fd(b, pair[0], pair[0]);
                assert_se(r >= 0);

                r = sd_bus_set_server(b, true, SD_ID128_NULL);
                assert_se(r >= 0);
        } else {
                r = sd_bus_set_address(b, address);
                assert_se(r >= 0);

                r = sd_bus_set_bus_client(b, true);
                assert_se(r >= 0);
        }

        r = sd_bus_start(b);
        assert_se(r >= 0);

        if (type != TYPE_DIRECT) {
                r = sd_bus_get_unique_name(b, &unique);
                assert_se(r >= 0);

                server_name = strdup(unique);
                assert_se(server_name);
        }

        sync();
        setpriority(PRIO_PROCESS, 0, -19);

        pid = fork();
        assert_se(pid >= 0);

        if (pid == 0) {
                CPU_ZERO(&cpuset);
                CPU_SET(0, &cpuset);
                pthread_setaffinity_np(pthread_self(), sizeof(cpu_set_t), &cpuset);

                safe_close(bus_ref);
                sd_bus_unref(b);

                switch (mode) {
                case MODE_BISECT:
                        client_bisect(address, server_name);
                        break;

                case MODE_CHART:
                        client_chart(type, address, server_name, pair[1]);
                        break;
                }

                _exit(0);
        }

        CPU_ZERO(&cpuset);
        CPU_SET(1, &cpuset);
        pthread_setaffinity_np(pthread_self(), sizeof(cpu_set_t), &cpuset);

        server(b, &result);

        if (mode == MODE_BISECT)
                printf("Copying/memfd are equally fast at %zu bytes\n", result);

        assert_se(waitpid(pid, NULL, 0) == pid);

        safe_close(pair[1]);
        sd_bus_unref(b);

        return 0;
}


```

**Comment by zeenix** [comment]
Firstly, thanks so much for benchmarking for us! :+1: It's been on my todo.

> I found the performance is much worse than bus1 "dbus-broker" service on my OpenBMC platform "armv7-unknown-linux-gnueabihf",

Ouch. While I've not measured it, I felt like performance was better on my powerful laptop with 16 threads: zbus tests finished faster against busd than against dbus-broker). Can you also run them on a machine with more threads?

> Also, run two test in parallel, the performance also dropped like it's running on single thread(supposedly they shouldn't, as zbus support full parallelism, and I have a 2core SoC, and I can see the busd process is running in two threads from perf):

That's very interesting. The parallelism is very much there but it's left to the async runtime. busd currently uses tokio. The issue could be the opposite actually: since tokio is targeted more for servers, it might not perform the best on low-end machines. We could look into using another runtime (e.g `smol`) if that helps the performance.

In any case, it would be good to get benchmarks result on a more powerful machine and see if there is a diff.

Oh and just to be sure, I hope you ran against latest git main (ecfb268c3bb594f2a080df34d7214fd260f585fe)?

**Comment by yongbingchen** [comment]
@zeenix 
Thank you for prompt response!
I updated the issue report, for some detail and error I made yesterday -- and confirmed the source code version I am using is the same you mentioned.
I had zbus benchmark against the C/C++ version libsystemd based D-Bus benchmarks (against dbus-broker as broker service), zbus can get full benefit of parallelism (while the libsystemd based can not), on the same HW/SW platform for this test, so I don't think tokio/zbus is the problem.

I think the main difference between your benchmark method with mine, is the client application: you are using zbus application, I am using libsystemd application (because in OpenBMC, all their services are using libsystemd) -- there may be some difference between the two, especially when doing marshalling/unmarshalling about the array of sized datas (in that test-bus-benchmark.c, it's calling sd_bus_message_append_array_space and sd_bus_message_read_array)

**Comment by zeenix** [comment]
> I had zbus benchmark against the C/C++ version libsystemd based D-Bus benchmarks (against dbus-broker as broker service), zbus can get full benefit of parallelism (while the libsystemd based can not), on the same HW/SW platform for this test, so I don't think tokio/zbus is the problem.

Yeah, I know. What I was saying was that zbus (that is doing most of the work for busd underneath) and busd itself rely on tokio's scheduling and since tokio mainly targets cloud servers, it's very much possible its scheduling does excessive context switching on low-end machines (with only 2 hardware threads) and that's a very sure way to kill the performance.

To clarify, what I wrote above is separate from what i wrote about the zbus (client side) tests. You're correct that those tests make use of the cores on my machine and hence not comparable to your benchmarking, but my point was that they *seem to* (remember it's completely based on visual impressions 😂) run faster against busd than dbus-broker. If this really is the case and given that the zbus tests do the same exact thing against both bus implementations, it very likely means that tokio indeed is the prime suspect here.

Hence why i think there's a need to repeat these benchmarks on more beefy machines.

**Comment by zeenix** [comment]
Another culprit could be zvariant (the underlying library used by zbus to encode and decode messages) which atm isn't the most performant (it's on my todo to optimise those bits). busd doesn't bother with the message body but it needs to parse the headers (it's zbus doing that for us so at least there is no double decoding).

**Comment by zeenix** [comment]
I wrote a [simple test application](https://github.com/zeenix/dbus-bench) using zbus and ran the tests against all 3 brokers. It seems that busd is significantly slower in dealing with sequential messages from/to a single client but performs much better (sometimes even better than dbus-broker but only slightly) when it comes to handling multiple clients. I'm guessing that busd's use of separate tokio tasks for each connection utilizing all the 8 cores & 16 threads on my machine, is why busd is so good at handling multiple clients.

Next I'd do some profiling and hopefully add some (much needed) optimizations to zbus and see if they help. I'm pretty confident that if/once we make the single-client scenario as fast as it is for dbus-broker, we'll be leaps and bounds faster than dbus-broker in handling multiple clients (the typical scenario in practice).

**Comment by zeenix** [comment]
@yongbingchen if you could try and run my test application on your low-end ARM machine, that would be extremely helpful. You'll probably need to use [`cross`](https://github.com/cross-rs/cross) instead of `cargo` to cross-compile but I'm guessing you already do that for busd so you know. :)

**Comment by zeenix** [comment]
Oh my! I'm very glad to report that the results I reported earlier here were from benchmarking against busd built in debug mode (and hence it was missing a lot of compiler optimizations). When built in release mode, the performance of busd is very similar (and sometimes even better) compared to the other 2 implementations.

Could you please repeat your benchmarks but with busd built with release mode?

**Comment by zeenix** [comment]
I'm closing this. I can always reopen if needed.
