### ISSUE TITLE
status of busd

### ISSUE THREAD

**Issue by keepitupkitty** [dbus2/busd#31]
Hello, I've found ur project yesterday and I am wondering if it's possible to replace dbus-daemon completely with this thing? how fast is it than dbus-broker? is there support of systemd integration?

**Comment by zeenix** [comment]
> f it's possible to replace dbus-daemon completely with this thing?

Not yet.



> how fast is it than dbus-broker?

Don't know.

> is there support of systemd integration?

Not yet.
